require("alexandersoen.options")
require("alexandersoen.remap")
require("alexandersoen.plugins")
require("alexandersoen.colorscheme")
-- require("alexandersoen.cmp")
-- require("alexandersoen.lsp")
require("alexandersoen.lspzero")
require("alexandersoen.nullls")
require("alexandersoen.telescope")
require("alexandersoen.harpoon")
require("alexandersoen.gitsigns")
-- require("alexandersoen.bufferline")

require("alexandersoen.lualine")
-- require("alexandersoen.neotree")
require("alexandersoen.treesitter")
